"""Initial schema

Revision ID: eacb0b79fb38
Revises:
Create Date: 2026-06-22 17:48:03.429875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.core.models import GUID


# revision identifiers, used by Alembic.
revision: str = 'eacb0b79fb38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('health_checks',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('service_id', GUID(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('service_id', GUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slos',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('service_id', GUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_availability', sa.Float(), nullable=True),
    sa.Column('window_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slos')
    op.drop_table('incidents')
    op.drop_table('health_checks')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
