apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reliability-hub.fullname" . }}-db-secret
  labels:
    {{- include "reliability-hub.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.databaseUrl | b64enc | quote }}
